# Ex1 - Filtrar y ordenar datos


### Paso 1. Importar las bibliotecas necesarias

In [26]:
import pandas as pd 
import numpy as numpy
import matplotlib as plt

### Paso 2. Importa el conjunto de datos de esta [dirección](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) y asígnalos a una variable llamada chipo.

In [27]:
import ssl # bypass certiicate
ssl._create_default_https_context = ssl._create_unverified_context

In [28]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv",sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [29]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Paso 3. Nombre del producto de valor máximo

In [30]:
max(chipo.item_price)

'$9.39 '

In [31]:
max_value = chipo['item_price'].max()
max_product = chipo.loc[chipo['item_price'].idxmax(), 'item_name']
max_value

'$9.39 '

In [10]:
x = chipo.item_price[chipo.item_price == max(chipo.item_price)]
x

607     $9.39
1418    $9.39
1421    $9.39
1825    $9.39
1865    $9.39
2600    $9.39
2624    $9.39
3098    $9.39
3115    $9.39
3356    $9.39
4036    $9.39
4241    $9.39
4390    $9.39
4391    $9.39
4419    $9.39
4547    $9.39
4572    $9.39
Name: item_price, dtype: object

### Paso 4. ¿Cuántos productos cuestan más de 10 dólares?

In [32]:
import pandas as pd

In [33]:

chipo[chipo.item_price == (chipo.item_price)][['item_name', 'item_price']].drop_duplicates()
# chipo['product_price'] = chipo.item_price / chipo.quantity

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39
1                                      Izze     $3.39
2                          Nantucket Nectar     $3.39
3     Chips and Tomatillo-Green Chili Salsa     $2.39
4                              Chicken Bowl    $16.98
...                                     ...        ...
4237                    Chips and Guacamole     $8.50
4354                       Steak Soft Tacos    $18.50
4489                    Chips and Guacamole    $17.80
4509                                  Chips     $1.99
4510                          Barbacoa Bowl    $11.49

[209 rows x 2 columns]

In [ ]:
chipo.drop(['item_name]',axis=1)

Extra: Cuántos pedidos se han hecho con un producto de más de 10$

### Paso 5. ¿Cuál es el precio de cada artículo? Obtenga sólo item_name y unit_price

In [34]:
chipo[['item_name', 'item_price']].sort_values(by='item_price', ascending=False)

                item_name item_price
2624     Steak Salad Bowl     $9.39
4419     Steak Salad Bowl     $9.39
4036     Steak Salad Bowl     $9.39
1825  Barbacoa Salad Bowl     $9.39
3115  Carnitas Salad Bowl     $9.39
...                   ...        ...
3145          Canned Soda     $1.09
414           Canned Soda     $1.09
3162          Canned Soda     $1.09
821           Canned Soda     $1.09
1457          Canned Soda     $1.09

[4622 rows x 2 columns]

### Paso 6. Ordenar por el nombre del artículo

In [36]:
chipo.item_name.sort_values()

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
              ...
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, Length: 4622, dtype: object

### Paso 7. ¿Cuál fue la cantidad del artículo más caro pedido? 2 formas

In [ ]:
chipo.groupby('order_id').sum().sort_values('item_price',ascending=False)

### Paso 8. ¿Cuántas veces se pidió una Veggie Salad Bowl?

In [40]:

chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]

len(chipo_salad)

### Paso 9. ¿Cuántas veces pidió alguien más de un Canned Soda?

Extra

In [ ]:
# 1º Filtrar con una máscara: chipo[chipo["item_name"] == "Canned Soda"]
# 2º Agrupar las orders y canned sodas sumando las cantitades totales .groupby(['order_id','item_name'], as_index= False)
# 3º Quiero sumar solo la columna de quantity [['quantity']].sum()

In [41]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]

len(chipo_salad)

18

In [42]:
chipo.where(chipo.item_name == "Veggie Salad Bowl").groupby("item_name").sum()

,order_id,quantity,choice_description,item_price
item_name,,,,
Veggie Salad Bowl,17303.0,18.0,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25 $11.25 $11.25 $11.25 $8.75 $8.75 $11.25...

In [43]:
chipo.item_name.value_counts()["Veggie Salad Bowl"]

18

In [44]:
chipo8 = chipo.groupby("item_name").sum()
chipo8.sort_values("quantity", ascending=False)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...
Chicken Burrito,497303,591,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49 $8.49 $10.98 $8.49 $10.98 $10.98 $8.75 $...
Chips and Guacamole,449959,506,0,$4.45 $4.45 $4.45 $4.45 $4.45 $3.99 $4.45 $3.9...
Steak Burrito,328437,386,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75 $9.25 $8.99 $11.75 $8.99 $8.99 $8.99 $8...
Canned Soft Drink,304753,351,[Coke][Sprite][Coke][Coke][Lemonade][Sprite][D...,$1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.2...
Chips,208004,230,0,$2.15 $2.15 $2.15 $2.15 $2.15 $2.15 $4.30 $2.1...
Steak Bowl,193752,221,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.99 $8.99 $11.75 $11.75 $8.99 $11.48 $9.25 $...
Bottled Water,175944,211,0,$1.09 $1.09 $1.09 $1.50 $1.50 $1.50 $3.00 $1.5...
Chips and Fresh Tomato Salsa,100419,130,0,$2.39 $2.39 $2.39 $2.95 $2.95 $2.95 $2.95 $2.3...
Canned Soda,76396,126,[Sprite][Dr. Pepper][Mountain Dew][Sprite][Dr....,$2.18 $1.09 $2.18 $1.09 $1.09 $1.09 $1.09 $2.1...
Chicken Salad Bowl,117104,123,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75 $22.50 $22.50 $8.75 $17.50 $8.75 $8.75 $...
Chicken Soft Tacos,98395,120,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75 $8.75 $8.75 $8.75 $11.25 $8.49 $8.49 $8....
Side of Chips,84769,110,0,$1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.6...
Veggie Burrito,80962,97,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25 $8.49 $11.25 $11.25 $10.98 $8.49 $8.49 ...
Barbacoa Burrito,74718,91,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99 $9.25 $9.25 $11.75 $11.75 $9.25 $8.99 $1...
Veggie Bowl,72270,87,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25 $8.49 $11.25 $11.25 $8.49 $11.25 $11.25...
Carnitas Bowl,62742,71,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99 $11.75 $9.25 $11.48 $8.99 $8.99 $23.50 $...
Barbacoa Bowl,53972,66,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75 $11.75 $9.25 $8.99 $9.25 $11.75 $9.25 $...
Carnitas Burrito,51652,60,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99 $9.25 $11.75 $9.25 $9.25 $9.25 $11.75 $9...
Steak Soft Tacos,50177,56,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25 $9.25 $8.99 $9.25 $8.99 $8.99 $9.25 $9.2...
6 Pack Soft Drink,52322,55,[Sprite][Diet Coke][Coke][Diet Coke][Diet Coke...,$6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.4...
Chips and Tomatillo Red Chili Salsa,45556,50,0,$2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.9...
Chicken Crispy Tacos,47382,50,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75 $17.50 $11.25 $8.49 $8.49 $11.25 $8.75 $...
Chips and Tomatillo Green Chili Salsa,41170,45,0,$2.95 $2.95 $5.90 $2.95 $2.95 $2.95 $2.95 $2.9...
Carnitas Soft Tacos,37673,40,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$9.25 $9.25 $9.25 $9.25 $9.25 $8.99 $8.99 $8.9...
Steak Crispy Tacos,35818,36,"[Fresh Tomato Salsa, Sour Cream][[Roasted Chil...",$9.25 $8.99 $9.25 $8.69 $8.99 $9.25 $8.99 $9.2...
Chips and Tomatillo-Green Chili Salsa,21826,33,0,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Steak Salad Bowl,29590,31,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$23.78 $11.89 $9.39 $23.78 $11.89 $11.89 $11.8...
Nantucket Nectar,21814,29,[Apple][Pomegranate Cherry][Pineapple Orange B...,$3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $6.78 $3.3...
Chips and Tomatillo-Red Chili Salsa,18344,25,0,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Barbacoa Soft Tacos,18725,25,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$9.25 $9.25 $8.99 $9.25 $9.25 $11.75 $11.75 $9...
Chips and Roasted Chili Corn Salsa,14999,23,0,$2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.9...
Izze,10587,20,[Clementine][Grapefruit][Blackberry][Blackberr...,$3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.3...
Veggie Salad Bowl,17303,18,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25 $11.25 $11.25 $11.25 $8.75 $8.75 $11.25...
Chips and Roasted Chili-Corn Salsa,17462,18,0,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Barbacoa Crispy Tacos,5613,12,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75 $9.25 $11.48 $11.75 $9.25 $9.25 $8.99 $...
Barbacoa Salad Bowl,9708,10,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.89 $11.89 $9.39 $9.39 $9.39 $11.89 $11.89 ...
Chicken Salad,10465,9,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$10.98 $10.98 $8.49 $8.49 $8.49 $8.49 $8.49 $8...
Carnitas Crispy Tacos,5868,8,[Roasted Chili Corn Salsa][Tomatillo Green Chi...,$9.25 $11.75 $8.99 $11.75 $8.99 $17.98 $9.25
Veggie Soft Tacos,5520,8,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25 $8.75 $8.49 $11.25 $8.75 $8.49 $16.98
Burrito,1550,6,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",$7.40 $7.40 $7.40 $7.40 $7.40 $7.40
Veggie Salad,7265,6,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.49 $8.49 $8.49 $8.49 $8.49 $8.49
Carnitas Salad Bowl,6693,6,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89 $9.39 $11.89 $9.39 $11.89 $11.89
Bowl,472,4,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20 $7.40
Steak Salad,2362,4,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99 $8.99 $8.99 $8.69
Salad,1150,2,"[Brown Rice, Adobo-Marinated and Grilled Chick...",$7.40 $7.40
Crispy Tacos,434,2,[Adobo-Marinated and Grilled Steak][Adobo-Mari...,$7.40 $7.40
Chips and Mild Fresh Tomato Salsa,279,1,0,$3.00
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49